### ISSUE TITLE
Reliability Score weighted by Ridership layer changes to all black at certain zoom levels

### ISSUE THREAD

**Issue by smoran3** [dvrpc/RTPS#49]
I hate to be adding to the list at this point  - this is a weird one. I noticed it at SEPTA today when trying to bring one of their new people up to speed. It also happens on the staging server. It looks fine when you first turn it on at the default extent, but as you zoom in, chunks start turning all black and then all the linework is black.

**Comment by mmolta** [comment]
The black linework is the result of the new vector tiles having some different field names than the old ones (i.e. riderrelis instead of weighted), and the code was styling based off of those names. Sean is updating the tile names now so it should be resolved. There might be some residual stuff for a little bit at certain zoom levels due to the way vector tiles cache stuff, but the issue itself will be fixed.

**Comment by seandoesgis** [comment]
Fixed field name in weighted layer
